name: Get Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          lfs: true
      - name: Set git identity
        run : |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm start
      - name: Push
        env:
          TZ: Asia/Shanghai
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          if [ "$(git status -s)" != "" ];then
            cdnChanged=$(git status -s | grep -e "docs/cdn/")
            git add .
            git commit -m "Daily Sync"
            git push origin main
            if [ "$cdnChanged" != "" ];then
              version=$(cat docs/cdn/version)
              git tag -a $version -m "update"
              git push origin $version
            fi
            cd docs
            git init
            git add -A
            git commit -m "Daily Sync"
            git push -u "https://x-access-token:${GITHUB_TOKEN}@github.com/HCLonely/pcr-jp-rank.git" HEAD:gh-pages --force
          fi
