name: Get Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Set git identity
        run : |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm start
      - name: Push
        env:
          TZ: Asia/Shanghai
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: node src/pushDocs.js
