name: Get Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,22 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          lfs: true
      - name: Set git identity
        run : |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm start
      - name: Push
        env:
          TZ: Asia/Shanghai
        run: |
          cdnChanged=$(git status -s | grep -e "docs/cdn/")
          if [ "$cdnChanged" != "" ];then
            version=$(cat docs/cdn/version)
            git add .
            git tag -a $version -m "update"
            git push origin $version
          fi
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
