name: Get Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          lfs: true
      - name: Set git identity
        run : |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm start
      - name: Push Commits
        env:
          TZ: Asia/Shanghai
        run: |
          if [ -n "$(git status -s)" ];then
            git add .
            git commit -m "Daily Sync"
            git push origin main
            if git status -s | grep -e "docs/cdn/";then
              version=$(cat docs/cdn/version)
              git tag -a $version
              git push origin $version
            fi
          fi
